# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [45]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [46]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(r"C:\Users\reide\Downloads\MAINUTOR-VIRT-FIN-PT-11-2022-U-LOLC\13-Neural-Networks\Unit 13 Homework\Instructions\Starter_Code\Resources\applicants_data.csv")

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [47]:
# Review the data types associated with the columns
# YOUR CODE HERE

applicant_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [48]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])

# Review the DataFrame
# YOUR CODE HERE

applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [49]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == 'object'].index)
                         

# Display the categorical variables list
# YOUR CODE HERE

categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [50]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [51]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [52]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data, columns=enc.get_feature_names(categorical_variables))

# Review the DataFrame
# YOUR CODE HERE

encoded_df

C:\Users\reide\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [53]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical_variables = applicant_data_df.drop(columns = categorical_variables)

encoded_df = pd.concat([encoded_df, numerical_variables], axis="columns")

# Review the Dataframe
# YOUR CODE HERE
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [54]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
# YOUR CODE HERE
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [55]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns = ["IS_SUCCESSFUL"])

# Review the features DataFrame
# YOUR CODE HERE
X

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179

### Step 6: Split the features and target sets into training and testing datasets.

In [56]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [57]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [58]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [59]:
# Define the number of neurons in the output layer
number_output_neurons = 2

In [60]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1)//2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [61]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (number_input_features + 1)//2
# Review the number hidden nodes in the second layer
hidden_nodes_layer2

58

In [62]:
# Create the Sequential model instance
nn = Sequential()

In [63]:
# Add the first hidden layer
# YOUR CODE HERE

nn.add(Dense(units = hidden_nodes_layer1  ,input_dim=number_input_features, activation='relu'))

In [64]:
# Add the second hidden layer
# YOUR CODE HERE

nn.add(Dense(units=hidden_nodes_layer2, input_dim=number_input_features, activation='relu'))

In [65]:
# Add the output layer to the model specifying the number of output neurons and activation function
# YOUR CODE HERE

nn.add(Dense(units="1", activation="sigmoid"))

In [66]:
# Display the Sequential model summary
# YOUR CODE HERE

nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 58)                6786

 dense_8 (Dense)             (None, 58)                3422

 dense_9 (Dense)             (None, 1)                 59

=================================================================
Total params: 10,267
Trainable params: 10,267
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [67]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer = "adam", metrics=["accuracy"])

In [68]:
# Fit the model using 50 epochs and the training data
# YOUR CODE HERE

fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.5786 - accuracy: 0.7204
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5525 - accuracy: 0.7311
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7302
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7317
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5456 - accuracy: 0.7317
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7346
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7342
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7352
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7339
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7357
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7355
Epoch 12/100
804/804 [==============================] - 1s 990us/step - loss: 0.5408 - accuracy: 0.7357
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7357
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7350
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7379
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7374
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5378 - accuracy: 0.7376
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7387
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7383
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7374
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7385
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7386
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7383
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7400
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7395
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7393
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7389
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7386
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7394
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7404
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7399
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7398
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7407
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7401
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7399
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7392
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7413
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7407
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7407
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7408
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7411
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7407
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7406
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7406
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7415
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7402
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7421
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7407
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7423
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7422
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7416
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7414
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5308 - accuracy: 0.7418
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7420
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5305 - accuracy: 0.7420
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5301 - accuracy: 0.7425
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5304 - accuracy: 0.7420
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5301 - accuracy: 0.7420
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5301 - accuracy: 0.7411
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5298 - accuracy: 0.7419
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5294 - accuracy: 0.7418
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5297 - accuracy: 0.7410
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5295 - accuracy: 0.7421
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5293 - accuracy: 0.7429
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5292 - accuracy: 0.7420
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5293 - accuracy: 0.7420
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7423
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5291 - accuracy: 0.7423
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5293 - accuracy: 0.7414
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5293 - accuracy: 0.7418
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5288 - accuracy: 0.7421
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5286 - accuracy: 0.7422
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5285 - accuracy: 0.7417
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5284 - accuracy: 0.7428
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5288 - accuracy: 0.7415
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5288 - accuracy: 0.7424
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5285 - accuracy: 0.7430
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5286 - accuracy: 0.7416
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5280 - accuracy: 0.7421
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5287 - accuracy: 0.7417
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5277 - accuracy: 0.7428
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5284 - accuracy: 0.7428
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5278 - accuracy: 0.7432
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5280 - accuracy: 0.7428
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5278 - accuracy: 0.7430
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5277 - accuracy: 0.7428
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5279 - accuracy: 0.7426
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5280 - accuracy: 0.7418
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5278 - accuracy: 0.7424
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5279 - accuracy: 0.7428
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5274 - accuracy: 0.7424
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5284 - accuracy: 0.7428
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5270 - accuracy: 0.7431
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5280 - accuracy: 0.7423
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5273 - accuracy: 0.7422
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5275 - accuracy: 0.7423
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5272 - accuracy: 0.7431
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5272 - accuracy: 0.7434
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5269 - accuracy: 0.7426
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5277 - accuracy: 0.7434

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [69]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5678 - accuracy: 0.7294 - 257ms/epoch - 960us/step
Loss: 0.5678179860115051, Accuracy: 0.7294460535049438

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [70]:
# Set the model's file path
file_path = "AlphabetSoup.h5"

# Export your model to a HDF5 file

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [71]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [72]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 3

In [73]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features + 1)//3

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

39

In [74]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [75]:
# First hidden layer
# YOUR CODE HERE

nn_A1.add(Dense(units=hidden_nodes_layer1_A1,input_dim=number_input_features, activation="relu"))

# Output layer
# YOUR CODE HERE

nn_A1.add(Dense(units="1", activation="sigmoid"))
# Check the structure of the model
# YOUR CODE HERE

nn_A1.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_10 (Dense)            (None, 39)                4563

 dense_11 (Dense)            (None, 1)                 40

=================================================================
Total params: 4,603
Trainable params: 4,603
Non-trainable params: 0
_________________________________________________________________

In [76]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics= ["accuracy"])

In [77]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5958 - accuracy: 0.7165
Epoch 2/50
804/804 [==============================] - 1s 909us/step - loss: 0.5600 - accuracy: 0.7285
Epoch 3/50
804/804 [==============================] - 1s 924us/step - loss: 0.5545 - accuracy: 0.7299
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5523 - accuracy: 0.7300
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5507 - accuracy: 0.7320
Epoch 6/50
804/804 [==============================] - 1s 902us/step - loss: 0.5497 - accuracy: 0.7315
Epoch 7/50
804/804 [==============================] - 1s 891us/step - loss: 0.5486 - accuracy: 0.7318
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7318
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7331
Epoch 10/50
804/804 [==============================] - 1s 898us/step - loss: 0.5466 - accuracy: 0.7334
Epoch 11/50
804/804 [==============================] - 1s 901us/step - loss: 0.5464 - accuracy: 0.7327
Epoch 12/50
804/804 [==============================] - 1s 934us/step - loss: 0.5455 - accuracy: 0.7323
Epoch 13/50
804/804 [==============================] - 1s 943us/step - loss: 0.5444 - accuracy: 0.7334
Epoch 14/50
804/804 [==============================] - 1s 986us/step - loss: 0.5447 - accuracy: 0.7340
Epoch 15/50
804/804 [==============================] - 1s 911us/step - loss: 0.5439 - accuracy: 0.7341
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7345
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7348
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7344
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7352
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7354
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7346
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7366
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7349
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7350
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7355
Epoch 26/50
804/804 [==============================] - 1s 991us/step - loss: 0.5419 - accuracy: 0.7365
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7366
Epoch 28/50
804/804 [==============================] - 1s 968us/step - loss: 0.5417 - accuracy: 0.7357
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7357
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7367
Epoch 31/50
804/804 [==============================] - 1s 959us/step - loss: 0.5407 - accuracy: 0.7364
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7368
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7375
Epoch 34/50
804/804 [==============================] - 1s 949us/step - loss: 0.5406 - accuracy: 0.7362
Epoch 35/50
804/804 [==============================] - 1s 922us/step - loss: 0.5404 - accuracy: 0.7365
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7367
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7369
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7365
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7373
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7374
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7359
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7369
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7365
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7375
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 46/50
804/804 [==============================] - 1s 940us/step - loss: 0.5385 - accuracy: 0.7377
Epoch 47/50
804/804 [==============================] - 1s 966us/step - loss: 0.5392 - accuracy: 0.7369
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7366
Epoch 49/50
804/804 [==============================] - 1s 978us/step - loss: 0.5390 - accuracy: 0.7369
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7382

#### Alternative Model 2

In [78]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [79]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 4

In [80]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 5

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

5

In [81]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [82]:
# First hidden layer
# YOUR CODE HERE

nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim = number_input_features, activation = "relu"))

# Output layer
# YOUR CODE HERE
       
nn_A2.add(Dense(units="1", activation = "sigmoid"))

# Check the structure of the model
# YOUR CODE HERE

nn_A2.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 5)                 585

 dense_13 (Dense)            (None, 1)                 6

=================================================================
Total params: 591
Trainable params: 591
Non-trainable params: 0
_________________________________________________________________

In [83]:
# Compile the model
# YOUR CODE HERE

nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [84]:
# Fit the model
# YOUR CODE HERE
nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 945us/step - loss: 0.6108 - accuracy: 0.7037
Epoch 2/50
804/804 [==============================] - 1s 880us/step - loss: 0.5692 - accuracy: 0.7250
Epoch 3/50
804/804 [==============================] - 1s 912us/step - loss: 0.5624 - accuracy: 0.7261
Epoch 4/50
804/804 [==============================] - 1s 924us/step - loss: 0.5592 - accuracy: 0.7267
Epoch 5/50
804/804 [==============================] - 1s 890us/step - loss: 0.5567 - accuracy: 0.7273
Epoch 6/50
804/804 [==============================] - 1s 900us/step - loss: 0.5542 - accuracy: 0.7269
Epoch 7/50
804/804 [==============================] - 1s 882us/step - loss: 0.5536 - accuracy: 0.7269
Epoch 8/50
804/804 [==============================] - 1s 925us/step - loss: 0.5523 - accuracy: 0.7269
Epoch 9/50
804/804 [==============================] - 1s 912us/step - loss: 0.5519 - accuracy: 0.7271
Epoch 10/50
804/804 [==============================] - 1s 883us/step - loss: 0.5515 - accuracy: 0.7275
Epoch 11/50
804/804 [==============================] - 1s 943us/step - loss: 0.5508 - accuracy: 0.7273
Epoch 12/50
804/804 [==============================] - 1s 943us/step - loss: 0.5506 - accuracy: 0.7275
Epoch 13/50
804/804 [==============================] - 1s 993us/step - loss: 0.5504 - accuracy: 0.7281
Epoch 14/50
804/804 [==============================] - 1s 871us/step - loss: 0.5502 - accuracy: 0.7271
Epoch 15/50
804/804 [==============================] - 1s 874us/step - loss: 0.5500 - accuracy: 0.7277
Epoch 16/50
804/804 [==============================] - 1s 953us/step - loss: 0.5497 - accuracy: 0.7278
Epoch 17/50
804/804 [==============================] - 1s 935us/step - loss: 0.5495 - accuracy: 0.7277
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7278
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5491 - accuracy: 0.7268
Epoch 20/50
804/804 [==============================] - 1s 959us/step - loss: 0.5489 - accuracy: 0.7311
Epoch 21/50
804/804 [==============================] - 1s 901us/step - loss: 0.5488 - accuracy: 0.7304
Epoch 22/50
804/804 [==============================] - 1s 898us/step - loss: 0.5484 - accuracy: 0.7306
Epoch 23/50
804/804 [==============================] - 1s 946us/step - loss: 0.5483 - accuracy: 0.7313
Epoch 24/50
804/804 [==============================] - 1s 871us/step - loss: 0.5483 - accuracy: 0.7313
Epoch 25/50
804/804 [==============================] - 1s 889us/step - loss: 0.5482 - accuracy: 0.7299
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7312
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7312
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7314
Epoch 29/50
804/804 [==============================] - 1s 892us/step - loss: 0.5471 - accuracy: 0.7307
Epoch 30/50
804/804 [==============================] - 1s 893us/step - loss: 0.5471 - accuracy: 0.7312
Epoch 31/50
804/804 [==============================] - 1s 887us/step - loss: 0.5469 - accuracy: 0.7318
Epoch 32/50
804/804 [==============================] - 1s 920us/step - loss: 0.5469 - accuracy: 0.7318
Epoch 33/50
804/804 [==============================] - 1s 970us/step - loss: 0.5469 - accuracy: 0.7324
Epoch 34/50
804/804 [==============================] - 1s 893us/step - loss: 0.5467 - accuracy: 0.7319
Epoch 35/50
804/804 [==============================] - 1s 901us/step - loss: 0.5463 - accuracy: 0.7326
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5465 - accuracy: 0.7318
Epoch 37/50
804/804 [==============================] - 1s 997us/step - loss: 0.5461 - accuracy: 0.7324
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7324
Epoch 39/50
804/804 [==============================] - 1s 941us/step - loss: 0.5460 - accuracy: 0.7322
Epoch 40/50
804/804 [==============================] - 1s 953us/step - loss: 0.5461 - accuracy: 0.7328
Epoch 41/50
804/804 [==============================] - 1s 934us/step - loss: 0.5462 - accuracy: 0.7320
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7327
Epoch 43/50
804/804 [==============================] - 1s 913us/step - loss: 0.5457 - accuracy: 0.7328
Epoch 44/50
804/804 [==============================] - 1s 902us/step - loss: 0.5462 - accuracy: 0.7327
Epoch 45/50
804/804 [==============================] - 1s 907us/step - loss: 0.5460 - accuracy: 0.7323
Epoch 46/50
804/804 [==============================] - 1s 912us/step - loss: 0.5458 - accuracy: 0.7325
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7322
Epoch 48/50
804/804 [==============================] - 1s 907us/step - loss: 0.5457 - accuracy: 0.7330
Epoch 49/50
804/804 [==============================] - 1s 884us/step - loss: 0.5458 - accuracy: 0.7328
Epoch 50/50
804/804 [==============================] - 1s 879us/step - loss: 0.5457 - accuracy: 0.7329

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [85]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5678 - accuracy: 0.7294 - 190ms/epoch - 709us/step
Loss: 0.5678179860115051, Accuracy: 0.7294460535049438

In [86]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5590 - accuracy: 0.7294 - 265ms/epoch - 989us/step
Loss: 0.5589998960494995, Accuracy: 0.7294460535049438

In [87]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5586 - accuracy: 0.7301 - 280ms/epoch - 1ms/step
Loss: 0.5585896372795105, Accuracy: 0.7301457524299622

### Step 3: Save each of your alternative models as an HDF5 file.

In [88]:
# Set the file path for the first alternative model
file_path = # YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE

SyntaxError: invalid syntax (839220193.py, line 2)

In [ ]:
# Set the file path for the second alternative model
file_path = # YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE